### ISSUE TITLE
Hey...

### ISSUE THREAD

**Issue by ghost** [busticated/dotfilez#2]
Hey, I'm very sorry to use this way to message you, but since GitHub has no private message feature, I felt forced to do so...
I just saw your comment on [this VSCode issue](https://github.com/microsoft/vscode/issues/53339) and I am experiencing the same problem and apparently the problem statement was not understood by the guy who answered the issue...
Did you actually solve this issue since then?

**Comment by busticated** [comment]
@leontepe lol no, i don't think i ever did. sorry!
